<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property integer $status
 * @property string $email
 * @property string $reminder_hash
 * @property string $last_login_time
 * @property string $create_time
 * @property string $update_time
 * @property string $description
 * @property string[] $blobs
 *
 */
class UserDto extends BaseDto
{
    public $id;
    public $name;
    public $status;
    public $email;
    public $reminder_hash;
    public $last_login_time;
    public $create_time;
    public $update_time;
    public $description;
    public $blobs;

    protected static $safeAttributes = array('id', 'name', 'status', 'email', 'reminder_hash', 'last_login_time', 'create_time', 'update_time', 'description', 'blobs');
}